[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
fuzz = { runs = 256 }
evm_version = "paris"

[rpc_endpoints]
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/6orgrMmjxab0rc-KBnEfU"
base_mainnet = "https://base-mainnet.g.alchemy.com/v2/6orgrMmjxab0rc-KBnEfU"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base_mainnet = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
