name = "api"
main = "index.ts"
compatibility_date = "2025-09-04"
compatibility_flags = ["nodejs_compat"]

# Non-sensitive vars can go here
[vars]
ENVIRONMENT="dev"
DATABASE_URL="postgresql://neondb_owner:npg_4U5PwkBWZRcf@ep-crimson-glitter-adykpome-pooler.c-2.us-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
ADMIN_AUTH_TOKEN="xad-admin-token-2025-early-poc"
