name: API Deploy to Production

on:
  push:
    branches:
      - master
    paths:
      - 'apps/api/**'
      - '!apps/api/README.md'
      - '!apps/api/.env.example'
      - '!apps/api/wrangler.toml.example'
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: apps/api
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: |
          cd ../..
          bun install
      
      - name: Create wrangler.toml with production secrets
        run: |
          cat > wrangler.toml << EOF
          name = "${{ secrets.CF_WORKER_NAME || 'xad-api' }}"
          main = "index.ts"
          compatibility_date = "2025-09-04"
          compatibility_flags = ["nodejs_compat"]
          account_id = "${{ secrets.CF_ACCOUNT_ID }}"
          
          [env.production]
          name = "${{ secrets.CF_WORKER_NAME || 'xad-api' }}-production"
          
          [env.production.vars]
          ENVIRONMENT = "production"
          DATABASE_URL = "${{ secrets.DATABASE_URL }}"
          ADMIN_AUTH_TOKEN = "${{ secrets.ADMIN_AUTH_TOKEN }}"
          PRIVY_APP_ID = "${{ secrets.PRIVY_APP_ID }}"
          PRIVY_APP_SECRET = "${{ secrets.PRIVY_APP_SECRET }}"
          PRIVY_VERIFICATION_KEY = "${{ secrets.PRIVY_VERIFICATION_KEY }}"
          JWT_SECRET = "${{ secrets.JWT_SECRET }}"
          ESCROW_ADDRESS = "${{ secrets.ESCROW_ADDRESS }}"
          LOG_LEVEL = "info"
          
          [env.production.observability]
          enabled = true
          EOF
      
      - name: Deploy to Cloudflare Workers (Production)
        working-directory: apps/api
        run: bun run wrangler deploy --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      
      - name: Clean up sensitive files
        if: always()
        working-directory: apps/api
        run: rm -f wrangler.toml
      
      - name: Create deployment notification
        if: success()
        run: |
          echo "✅ API deployed to PRODUCTION environment"
          echo "Worker: ${{ secrets.CF_WORKER_NAME || 'xad-api' }}-production"
          echo "Deployment triggered by: ${{ github.actor }}"