name: API Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
    paths:
      - 'apps/api/**'
      - '!apps/api/README.md'
      - '!apps/api/.env.example'
      - '!apps/api/wrangler.toml.example'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    defaults:
      run:
        working-directory: apps/api
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: |
          cd ../..
          bun install
      
      - name: Create wrangler.toml with secrets
        run: |
          cat > wrangler.toml << EOF
          name = "${{ secrets.CF_WORKER_NAME || 'xad-api' }}"
          main = "index.ts"
          compatibility_date = "2025-09-04"
          compatibility_flags = ["nodejs_compat"]
          account_id = "${{ secrets.CF_ACCOUNT_ID }}"
          
          [env.production]
          name = "${{ secrets.CF_WORKER_NAME || 'xad-api' }}-production"
          logpush = true
          
          [env.production.vars]
          ENVIRONMENT = "production"
          DATABASE_URL = "${{ secrets.DATABASE_URL }}"
          ADMIN_AUTH_TOKEN = "${{ secrets.ADMIN_AUTH_TOKEN }}"
          PRIVY_APP_ID = "${{ secrets.PRIVY_APP_ID }}"
          PRIVY_APP_SECRET = "${{ secrets.PRIVY_APP_SECRET }}"
          LOG_LEVEL = "info"
          
          [env.staging]
          name = "${{ secrets.CF_WORKER_NAME || 'xad-api' }}-staging"
          logpush = true
          
          [env.staging.vars]
          ENVIRONMENT = "staging"
          DATABASE_URL = "${{ secrets.STAGING_DATABASE_URL || secrets.DATABASE_URL }}"
          ADMIN_AUTH_TOKEN = "${{ secrets.STAGING_ADMIN_AUTH_TOKEN || secrets.ADMIN_AUTH_TOKEN }}"
          PRIVY_APP_ID = "${{ secrets.STAGING_PRIVY_APP_ID || secrets.PRIVY_APP_ID }}"
          PRIVY_APP_SECRET = "${{ secrets.STAGING_PRIVY_APP_SECRET || secrets.PRIVY_APP_SECRET }}"
          LOG_LEVEL = "debug"
          EOF
      
      - name: Deploy to Cloudflare Workers (Production)
        if: github.event_name == 'push' || github.event.inputs.environment == 'production'
        working-directory: apps/api
        run: bun run wrangler deploy --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      
      - name: Deploy to Cloudflare Workers (Staging)
        if: github.event.inputs.environment == 'staging'
        working-directory: apps/api
        run: bun run wrangler deploy --env staging
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      
      - name: Clean up sensitive files
        if: always()
        working-directory: apps/api
        run: rm -f wrangler.toml
      
      - name: Create deployment notification
        if: success()
        run: |
          ENVIRONMENT="${{ github.event.inputs.environment || 'production' }}"
          echo "✅ API deployed to $ENVIRONMENT environment"
          echo "Worker: ${{ secrets.CF_WORKER_NAME || 'xad-api' }}-$ENVIRONMENT"
          echo "Deployment triggered by: ${{ github.actor }}"